name: ingles1000
description: "Aplicativo para aprender as 1000 frases mais comuns em inglês com repetição espaçada."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  fl_chart: ^0.55.2
  
  # Backend
  supabase_flutter: ^2.0.0
  
  # FSRS
  flutter_js: ^0.7.0  # Para executar fsrs.js
  
  # Importação .apkg
  archive: ^3.4.0      # Descompactar ZIP
  sqflite: ^2.3.0      # Ler SQLite do .apkg
  path_provider: ^2.1.1
  
  # Utilitários
  audioplayers: ^5.1.0
  file_picker: ^6.0.0  # Para selecionar .apkg
  url_launcher: ^6.2.0 # Para abrir URLs na tela About

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/svg/
    - assets/fonts/